const mongoose = require("mongoose");

const BookingSchema = new mongoose.Schema({
  customer_id: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
  package_id: { type: mongoose.Schema.Types.ObjectId, ref: "Package" },
  manager_id: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
  staff_ids: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  inquiry_id: { type: mongoose.Schema.Types.ObjectId, ref: "Inquiry" },
  event_type: String,
  event_theme: String,
  event_date: Date,
  start_time: String,
  guest_count: Number,
  duration_hours: Number,
  include_food: { type: Boolean, default: true },
  venue_type: String,
  indoor_outdoor: String,
  province: String,
  municipality: String,
  barangay: String,
  street: String,
  landmark: String,
  zip_code: String,
  venue_contact_name: String,
  venue_contact_phone: String,
  selected_menu: [String],
  dietary_restrictions: String,
  allergies: String,
  special_requests: String,
  additional_services: [String],
  contact_first_name: String,
  contact_last_name: String,
  contact_email: String,
  contact_phone: String,
  contact_alt_phone: String,
  contact_method: String,
  total_price: Number,
  payment_method: String,
  payment_status: { type: String, default: "pending" },
  status: { type: String, default: "active" }
}, { timestamps: true });

module.exports = mongoose.model("Booking", BookingSchema);