const mongoose = require("mongoose");

const QuoteSchema = new mongoose.Schema({
  customer_id: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
  service_type: String,
  event_type: String,
  event_theme: String,
  event_date: Date,
  start_time: String,
  guest_count: Number,
  duration_hours: Number,
  venue_type: String,
  venue_size: String,
  indoor_outdoor: String,
  province: String,
  municipality: String,
  barangay: String,
  street: String,
  landmark: String,
  zip_code: String,
  budget_range: String,
  furniture_setup: [String],
  dining_inventory: [String],
  add_ons: [String],
  lighting_options: [String],
  decor_options: [String],
  theme_colors: String,
  delivery_date: Date,
  delivery_time: String,
  delivery_method: String,
  pickup_date: Date,
  pickup_time: String,
  delivery_instructions: String,
  selected_menu: [String],
  menu_other: String,
  dietary_restrictions: String,
  allergies: String,
  full_name: String,
  email: String,
  phone: String,
  contact_method: String,
  best_time_to_call: String,
  inspiration_links: String,
  notes: String,
  status: { type: String, default: "pending" }
}, { timestamps: true });

module.exports = mongoose.model("Quote", QuoteSchema);
